<?php

namespace App\Providers;

use App\Models\Gender;
use App\WebRepositories\BankRepository;
use App\WebRepositories\BankToBankRepository;
use App\WebRepositories\CityRepository;
use App\WebRepositories\CompanyRepository;
use App\WebRepositories\CompanyTypeRepository;
use App\WebRepositories\CountryRepository;
use App\WebRepositories\CustomerAdvanceBookingRepository;
use App\WebRepositories\CustomerAdvanceRepository;
use App\WebRepositories\CustomerPricesRepository;
use App\WebRepositories\CustomerRepository;
use App\WebRepositories\DeliveryNoteRepository;
use App\WebRepositories\DepartmentRepository;
use App\WebRepositories\DepositRepository;
use App\WebRepositories\DesignationRepository;
use App\WebRepositories\DriverRepository;
use App\WebRepositories\EmployeeRepository;
use App\WebRepositories\EmployeeTransactionRepository;
use App\WebRepositories\ExpenseCategoryRepository;
use App\WebRepositories\ExpenseDetailRepository;
use App\WebRepositories\ExpenseDetailsRepository;
use App\WebRepositories\ExpenseRepository;
use App\WebRepositories\ExpensesRepository;
use App\WebRepositories\FileManagerRepository;
use App\WebRepositories\FinancerRepository;
use App\WebRepositories\GenderRepository;
use App\WebRepositories\GstRepository;
use App\WebRepositories\Interfaces\IBankRepositoryInterface;
use App\WebRepositories\Interfaces\IBankToBankRepositoryInterface;
use App\WebRepositories\Interfaces\ICityRepositoryInterface;
use App\WebRepositories\Interfaces\ICompanyRepositoryInterface;
use App\WebRepositories\Interfaces\ICompanyTypeRepositoryInterface;
use App\WebRepositories\Interfaces\ICountryRepositoryInterface;
use App\WebRepositories\Interfaces\ICustomerAdvanceBookingRepositoryInterface;
use App\WebRepositories\Interfaces\ICustomerAdvanceRepositoryInterface;
use App\WebRepositories\Interfaces\ICustomerPricesRepositoryInterface;
use App\WebRepositories\Interfaces\ICustomerRepositoryInterface;
use App\WebRepositories\Interfaces\IDeliveryNoteRepositoryInterface;
use App\WebRepositories\Interfaces\IDepartmentRepositoryInterface;
use App\WebRepositories\Interfaces\IDepositRepositoryInterface;
use App\WebRepositories\Interfaces\IDesignationRepositoryInterface;
use App\WebRepositories\Interfaces\IDriverRepositoryInterface;
use App\WebRepositories\Interfaces\IEmployeeRepositoryInterface;
use App\WebRepositories\Interfaces\IEmployeeTransactionRepositoryInterface;
use App\WebRepositories\Interfaces\IExpenseCategoryRepositoryInterface;
use App\WebRepositories\Interfaces\IExpenseDetailRepositoryInterface;
use App\WebRepositories\Interfaces\IExpenseDetailsRepositoryInterface;
use App\WebRepositories\Interfaces\IExpenseRepositoryInterface;
use App\WebRepositories\Interfaces\IExpensesRepositoryInterface;
use App\WebRepositories\Interfaces\IFileManagerRepositoryInterface;
use App\WebRepositories\Interfaces\IFinancerRepositoryInterface;
use App\WebRepositories\Interfaces\IGenderRepositoryInterface;
use App\WebRepositories\Interfaces\IGstRepositoryInterface;
use App\WebRepositories\Interfaces\IInvestorRepositoryInterface;
use App\WebRepositories\Interfaces\IInvestorTransactionRepositoryInterface;
use App\WebRepositories\Interfaces\IInwardLoanRepositoryInterface;
use App\WebRepositories\Interfaces\ILoanRepositoryInterface;
use App\WebRepositories\Interfaces\ILpoRepositoryInterface;
use App\WebRepositories\Interfaces\IMeterReaderRepositoryInterface;
use App\WebRepositories\Interfaces\IMeterReadingDetailRepositoryInterface;
use App\WebRepositories\Interfaces\IMeterReadingRepositoryInterface;
use App\WebRepositories\Interfaces\INationalityRepositoryInterface;
use App\WebRepositories\Interfaces\IOtherStockRepositoryInterface;
use App\WebRepositories\Interfaces\IOutwardLoandRepositoryInterface;
use App\WebRepositories\Interfaces\IPaymentReceiveDetailRepositoryInterface;
use App\WebRepositories\Interfaces\IPaymentReceiveRepositoryInterface;
use App\WebRepositories\Interfaces\IPaymentTermRepositoryInterface;
use App\WebRepositories\Interfaces\IPaymentTypeRepositoryInterface;
use App\WebRepositories\Interfaces\IProductRepositoryInterface;
use App\WebRepositories\Interfaces\IProformaInvoiceRepositoryInterface;
use App\WebRepositories\Interfaces\IProjectRepositoryInterface;
use App\WebRepositories\Interfaces\IPurchaseDetailRepositoryInterface;
use App\WebRepositories\Interfaces\IPurchaseInvoiceRepositoryInterface;
use App\WebRepositories\Interfaces\IPurchaseRepositoryInterface;
use App\WebRepositories\Interfaces\IQuotationRepositoryInterface;
use App\WebRepositories\Interfaces\IRegionRepositoryInterface;
use App\WebRepositories\Interfaces\IReportFileTypeRepositoryInterface;
use App\WebRepositories\Interfaces\IReportRepositoryInterface;
use App\WebRepositories\Interfaces\IRoleRepositoryInterface;
use App\WebRepositories\Interfaces\ISalaryRepositoryInterface;
use App\WebRepositories\Interfaces\ISaleDetailsRepositoryInterface;
use App\WebRepositories\Interfaces\ISaleRepositoryInterface;
use App\WebRepositories\Interfaces\IStatesRepositoryInterface;
use App\WebRepositories\Interfaces\ISupplierAdvanceRepositoryInterface;
use App\WebRepositories\Interfaces\ISupplierPaymentRepositoryDetailInterface;
use App\WebRepositories\Interfaces\ISupplierPaymentRepositoryInterface;
use App\WebRepositories\Interfaces\ISupplierRepositoryInterface;
use App\WebRepositories\Interfaces\ITaskFrequencyRepositoryInterface;
use App\WebRepositories\Interfaces\ITaskMasterRepositoryInterface;
use App\WebRepositories\Interfaces\ITaskRepositoryInterface;
use App\WebRepositories\Interfaces\ITaxInvoiceRepositoryInterface;
use App\WebRepositories\Interfaces\IUnitRepositoryInterface;
use App\WebRepositories\Interfaces\IUserRepositoryInterface;
use App\WebRepositories\Interfaces\IVaultRepositoryInterface;
use App\WebRepositories\Interfaces\IVehicleRepositoryInterface;
use App\WebRepositories\Interfaces\IWithdrawalRepositoryInterface;
use App\WebRepositories\InvestorRepository;
use App\WebRepositories\InvestorTransactionRepository;
use App\WebRepositories\InwardLoanRepository;
use App\WebRepositories\LoanRepository;
use App\WebRepositories\LpoRepository;
use App\WebRepositories\MeterReaderRepository;
use App\WebRepositories\MeterReadingDetailRepository;
use App\WebRepositories\MeterReadingRepository;
use App\WebRepositories\NationalityRepository;
use App\WebRepositories\OtherStockRepository;
use App\WebRepositories\OutwardLoanRepository;
use App\WebRepositories\PaymentReceiveDetailRepository;
use App\WebRepositories\PaymentReceiveRepository;
use App\WebRepositories\PaymentTermRepository;
use App\WebRepositories\PaymentTypeRepository;
use App\WebRepositories\ProductRepository;
use App\WebRepositories\ProformaInvoiceRepository;
use App\WebRepositories\ProjectRepository;
use App\WebRepositories\PurchaseDetailRepository;
use App\WebRepositories\PurchaseInvoiceRepository;
use App\WebRepositories\PurchaseRepository;
use App\WebRepositories\QuotationRepository;
use App\WebRepositories\RegionRepository;
use App\WebRepositories\ReportFileTypeRepository;
use App\WebRepositories\ReportRepository;
use App\WebRepositories\RoleRepository;
use App\WebRepositories\SalaryRepository;
use App\WebRepositories\SaleDetailsRepository;
use App\WebRepositories\SaleRepository;
use App\WebRepositories\StateRepository;
use App\WebRepositories\SupplierAdvanceRepository;
use App\WebRepositories\SupplierPaymentDetailRepository;
use App\WebRepositories\SupplierPaymentRepository;
use App\WebRepositories\SupplierRepository;
use App\WebRepositories\TaskFrequencyRepository;
use App\WebRepositories\TaskMasterRepository;
use App\WebRepositories\TaskRepository;
use App\WebRepositories\TaxInvoiceRepository;
use App\WebRepositories\UnitRepository;
use App\WebRepositories\UserRepository;
use App\WebRepositories\VaultRepository;
use App\WebRepositories\VehicleRepository;
use App\WebRepositories\WithdrawalRepository;
use Illuminate\Support\ServiceProvider;

class WebRepositoryServiceProvider extends ServiceProvider
{
    public function register()
    {
        $this->app->bind(IUserRepositoryInterface::class,UserRepository::class);
        $this->app->bind(IRoleRepositoryInterface::class, RoleRepository::class);
        $this->app->bind(ICompanyRepositoryInterface::class,CompanyRepository::class);
        $this->app->bind(ICustomerRepositoryInterface::class,CustomerRepository::class);
        $this->app->bind(IDriverRepositoryInterface::class, DriverRepository::class);
        $this->app->bind(IVehicleRepositoryInterface::class,VehicleRepository::class);
        $this->app->bind(ICustomerAdvanceRepositoryInterface::class,CustomerAdvanceRepository::class);
        $this->app->bind(ISupplierRepositoryInterface::class, SupplierRepository::class);
        $this->app->bind(ISupplierAdvanceRepositoryInterface::class, SupplierAdvanceRepository::class);
        $this->app->bind(IBankRepositoryInterface::class, BankRepository::class);
        $this->app->bind(ICountryRepositoryInterface::class, CountryRepository::class);
        $this->app->bind(IStatesRepositoryInterface::class, StateRepository::class);
        $this->app->bind(ICityRepositoryInterface::class, CityRepository::class);
        $this->app->bind(IRegionRepositoryInterface::class, RegionRepository::class);
        $this->app->bind(IUnitRepositoryInterface::class, UnitRepository::class);
        $this->app->bind(IProductRepositoryInterface::class, ProductRepository::class);
        $this->app->bind(IPurchaseRepositoryInterface::class, PurchaseRepository::class);
        $this->app->bind(IPurchaseDetailRepositoryInterface::class,PurchaseDetailRepository::class);
        $this->app->bind(IExpenseCategoryRepositoryInterface::class, ExpenseCategoryRepository::class);
        $this->app->bind(IEmployeeRepositoryInterface::class,EmployeeRepository::class);
        $this->app->bind(IExpensesRepositoryInterface::class, ExpensesRepository::class);
        $this->app->bind(IExpenseDetailsRepositoryInterface::class,ExpenseDetailsRepository::class);
        $this->app->bind(ISaleRepositoryInterface::class,SaleRepository::class);
        $this->app->bind(ISaleDetailsRepositoryInterface::class,SaleDetailsRepository::class);
        $this->app->bind(IMeterReaderRepositoryInterface::class, MeterReaderRepository::class);
        $this->app->bind(IMeterReadingRepositoryInterface::class, MeterReadingRepository::class);
        $this->app->bind(IMeterReadingDetailRepositoryInterface::class, MeterReadingDetailRepository::class);
        $this->app->bind(ILoanRepositoryInterface::class,LoanRepository::class);
        $this->app->bind(ICustomerPricesRepositoryInterface::class, CustomerPricesRepository::class);
        $this->app->bind(ICompanyTypeRepositoryInterface::class, CompanyTypeRepository::class);
        $this->app->bind(IPaymentTypeRepositoryInterface::class, PaymentTypeRepository::class);
        $this->app->bind(IPaymentTermRepositoryInterface::class,PaymentTermRepository::class);
        $this->app->bind(IPaymentReceiveRepositoryInterface::class, PaymentReceiveRepository::class);
        $this->app->bind(IPaymentReceiveDetailRepositoryInterface::class, PaymentReceiveDetailRepository::class);
        $this->app->bind(ISupplierPaymentRepositoryInterface::class, SupplierPaymentRepository::class);
        $this->app->bind(ISupplierPaymentRepositoryDetailInterface::class, SupplierPaymentDetailRepository::class);
        $this->app->bind(IReportRepositoryInterface::class,ReportRepository::class);
        $this->app->bind(IDepositRepositoryInterface::class,DepositRepository::class);
        $this->app->bind(IFinancerRepositoryInterface::class,FinancerRepository::class);
        $this->app->bind(IInwardLoanRepositoryInterface::class,InwardLoanRepository::class);
        $this->app->bind(IOutwardLoandRepositoryInterface::class,OutwardLoanRepository::class);
        $this->app->bind(IBankToBankRepositoryInterface::class,BankToBankRepository::class);
        $this->app->bind(IWithdrawalRepositoryInterface::class,WithdrawalRepository::class);
        $this->app->bind(IProjectRepositoryInterface::class,ProjectRepository::class);
        $this->app->bind(IQuotationRepositoryInterface::class,QuotationRepository::class);
        $this->app->bind(ILpoRepositoryInterface::class,LpoRepository::class);
        $this->app->bind(ITaxInvoiceRepositoryInterface::class,TaxInvoiceRepository::class);
        $this->app->bind(IProformaInvoiceRepositoryInterface::class,ProformaInvoiceRepository::class);
        $this->app->bind(IOtherStockRepositoryInterface::class,OtherStockRepository::class);
        $this->app->bind(IInvestorRepositoryInterface::class,InvestorRepository::class);
        $this->app->bind(IInvestorTransactionRepositoryInterface::class,InvestorTransactionRepository::class);
        $this->app->bind(IVaultRepositoryInterface::class,VaultRepository::class);
        $this->app->bind(ISalaryRepositoryInterface::class,SalaryRepository::class);
        $this->app->bind(IDeliveryNoteRepositoryInterface::class,DeliveryNoteRepository::class);
        $this->app->bind(ITaskFrequencyRepositoryInterface::class,TaskFrequencyRepository::class);
        $this->app->bind(ITaskMasterRepositoryInterface::class,TaskMasterRepository::class);
        $this->app->bind(ITaskRepositoryInterface::class,TaskRepository::class);
        $this->app->bind(ICustomerAdvanceBookingRepositoryInterface::class,CustomerAdvanceBookingRepository::class);
        $this->app->bind(IReportFileTypeRepositoryInterface::class,ReportFileTypeRepository::class);
        $this->app->bind(IFileManagerRepositoryInterface::class,FileManagerRepository::class);
        $this->app->bind(IPurchaseInvoiceRepositoryInterface::class,PurchaseInvoiceRepository::class);
        $this->app->bind(IDepartmentRepositoryInterface::class,DepartmentRepository::class);
        $this->app->bind(IDesignationRepositoryInterface::class,DesignationRepository::class);
        $this->app->bind(INationalityRepositoryInterface::class,NationalityRepository::class);
        $this->app->bind(IGenderRepositoryInterface::class,GenderRepository::class);
        $this->app->bind(IEmployeeTransactionRepositoryInterface::class,EmployeeTransactionRepository::class);
        $this->app->bind(IGstRepositoryInterface::class,GstRepository::class);
    }

    public function boot()
    {
        //
    }
}
